REVOKE EXECUTE ON FUNCTION public.generate_monthly_invoices(date) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_admins(text, text, text, uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_user(uuid, text, text, text, uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_cleaning_completed() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_cleaning_created() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_invoice_created() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_payment_created() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_tenant_created() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_visit_completed() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_visit_created() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_visit_doc() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.can_read_cleaning(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_assistant_of_prospect(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_my_cleaning(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_my_tenancy_property(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_my_tenant_row(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_my_visit(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.owns_property(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.owns_tenant_property(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.owns_visit_property(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon;