REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.owns_property(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_my_tenancy_property(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_my_tenant_row(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.owns_tenant_property(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_my_visit(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.owns_visit_property(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_assistant_of_prospect(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.can_read_cleaning(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_my_cleaning(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.notify_user(uuid, text, text, text, uuid) FROM anon, public, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_admins(text, text, text, uuid) FROM anon, public, authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_monthly_invoices(date) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.generate_monthly_invoices(date) TO authenticated;